version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(go):"
    groups:
      go-minor:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: gomod
    directory: /examples
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(examples):"
    groups:
      go-examples-minor:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(ci):"
    groups:
      actions-minor:
        patterns: ["*"]
        update-types: [minor, patch]
